### ISSUE TITLE
Upgrade show tests from pending to fact assertion

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#230]
These three tests were downgraded to pending in release 0.6.5. https://github.com/JuliaStats/TimeSeries.jl/blob/master/test/timearray.jl#L113

**Comment by milktrader** [comment]
@GordStephen I wouldn't mind removing these tests altogether. I don't think packages test their show methods, but I don't mind them if they can pass on travis.

**Comment by GordStephen** [comment]
Fine by me, the goal was just to be able to catch the kind of issue we had previously where `show`ing a 0-length TimeArray threw an error - maybe instead of asserting specific text output we could just call `show` in various contexts during testing (basically achieving the opposite of using `@fact_throws`)?

**Comment by GordStephen** [comment]
Implemented the above in #223
