### ISSUE TITLE
Overload Base.find

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeSeries.jl#232]
- [x] replace `by`
- [ ] replace `findwhen`
- [x] replace `findall` -- planned in the 0.7.0 branch

Maybe `findall` can stay and not be exported (and probably renamed to remove the word "find"). The idea behind it was that it's much faster indexing a time series with integers than DateType values (which is what `findwhen` does)

@GordStephen has already started down this path, so this should consolidate the discussion.

**Comment by GordStephen** [comment]
Personally I'd lean towards keeping `find` reserved for a method that mirrors the functionality of `Base.find` - given an Array _or_ TimeArray of Bool, return an Int list of all indices of `true` values. Maybe there's a better name for a function that returns a TimeType list instead though - `findtimestamp` instead of `findwhen`? Not sure...

**Comment by milktrader** [comment]
So `findall` should just be `find`? I like your reasoning behind this, thanks. 

About `findwhen`, not sure ... what do you think about this?

````julia
find(ta::TimeArray{Bool,1}; list=:Int) 
list == :Int ? [conform to Base.find semantics] :
list == :TimeType ? [return a list of TimeType values] :
error("Only Int and TimeType values are supported")

````

**Comment by milktrader** [comment]
After thinking about the above example, I don't like it.

**Comment by milktrader** [comment]
Closing this for now
