### ISSUE TITLE
all(::TimeSeries)?

### ISSUE THREAD

**Issue by dourouc05** [JuliaStats/TimeSeries.jl#356]
Following a recent trend of addition of methods (like #338), would something like `all()`be interesting? I am currently comparing two time series, and a simple `==` generates a warning: 

```
WARNING: ==(ta::TimeArray, args...) is deprecated, use ==.(ta, args...) instead.
```

I have thus switched to `==.`, and I have a time series of Booleans, instead of a single Boolean. I would like `all(ta)` to return `all(ta.value)` when that makes sense (I am only thinking of having one Boolean column and no other column). Then, `any()` could be implemented similarly (and maybe others). 

This is more a request for comments; I can provide an implementation if you think this is worthwhile.

**Comment by iblis17** [comment]
> Following a recent trend of addition of methods (like #338), would something like `all()` be interesting?

I agree with that we should support more reduction functions like `all` and `any`,
but the next problem is the return type. Should it be a scalar, be a TimeArray or depends?

**Comment by dourouc05** [comment]
When there is only one column, I think the answer is quite obvious (take the `all` of the values of this single column). However, when there are multiple columns (only Booleans), it might make sense to do it line by line (i.e. return a new time series with just one column).

**Comment by iblis17** [comment]
First, for your need, I think we need to revoke the deprecation warning of `==` and redefine its meaning as 'Does two TimeArray share exactly same fields?`

Second, about `all`, `any` and etc, I will prefer to return a `TImeArray` like other reduction function (`sum`, `mean`) does. Since TimeArray is a tabular data structure and it has two dimesion,
in order to do reduction, you need to specificy the dimension (the default is along the columnes).
That what #338 does: e.g. `sum` give you a `TImeArray` with latest timestamp.
I want to keep consistent on `all` and `any`.
Futhermore, I will expect the reduction function shares same result with `moving(..., full_length)`
e.g. `moving(sum, cl, length(cl))` equals to `sum(cl)`.

**Comment by iblis17** [comment]
you might want to try out #359
